-- Schema inicial (baseline). Gerado a partir das entidades com o dialeto do
-- PostgreSQL e revisado à mão. Mudança de schema daqui em diante é V2, V3...
-- nunca editar este arquivo depois de aplicado.

create table usuarios (
    id         bigint generated by default as identity primary key,
    nome       varchar(80)  not null,
    email      varchar(160) not null,
    senha_hash varchar(255) not null,
    role       varchar(10)  not null check (role in ('USER', 'ADMIN')),
    constraint uk_usuarios_email unique (email)
);

create table produtos (
    id         bigint generated by default as identity primary key,
    nome       varchar(140)   not null,
    descricao  varchar(1000),
    preco      numeric(12, 2) not null check (preco > 0),
    estoque    integer        not null check (estoque >= 0),
    imagem_url varchar(300)
);
